// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package grpc_go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Users)(nil), "pb.Users")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0xd7, 0xba, 0xf5, 0x15, 0x44, 0x83, 0x87, 0x52, 0x50, 0xb7, 0x5e, 0xb6, 0x8b,
	0xad, 0xcc, 0x93, 0xc7, 0x0d, 0x64, 0x78, 0x9d, 0xec, 0x22, 0x5e, 0xda, 0xe6, 0x51, 0x03, 0x8d,
	0x0d, 0x49, 0x2a, 0xec, 0x7f, 0xf1, 0x8f, 0x95, 0xbc, 0x6d, 0x3d, 0xf5, 0xf6, 0x7d, 0x3f, 0x7e,
	0x09, 0x1f, 0x0f, 0x6e, 0x94, 0xee, 0x6c, 0x57, 0xf4, 0x06, 0x75, 0x4e, 0x91, 0xf9, 0xaa, 0xca,
	0xbe, 0x20, 0x38, 0x18, 0xd4, 0xec, 0x1a, 0x7c, 0xc1, 0x13, 0x6f, 0xee, 0xad, 0xa2, 0xbd, 0x2f,
	0x38, 0x4b, 0x61, 0xe6, 0xcc, 0x9f, 0x52, 0x62, 0xe2, 0x13, 0x1d, 0x3a, 0x63, 0x10, 0x10, 0x9f,
	0x10, 0xa7, 0xcc, 0xee, 0x20, 0x44, 0x59, 0x8a, 0x36, 0x09, 0x08, 0x9e, 0x4a, 0xb6, 0x84, 0xd0,
	0xfd, 0x6e, 0xd8, 0xc3, 0x39, 0x24, 0xde, 0x7c, 0xb2, 0x8a, 0xd7, 0xb3, 0x5c, 0x55, 0xb9, 0x03,
	0xfb, 0x13, 0xce, 0xa6, 0x10, 0xbe, 0x49, 0x65, 0x8f, 0xeb, 0x3f, 0x0f, 0x62, 0x87, 0x3e, 0x50,
	0xff, 0x8a, 0x1a, 0xd9, 0x3d, 0x4c, 0x37, 0x9c, 0xd3, 0xc4, 0xe1, 0x51, 0x3a, 0x24, 0xb6, 0x84,
	0xdb, 0x1d, 0x5a, 0x17, 0xb7, 0xc7, 0xc3, 0x65, 0xdf, 0x98, 0xb8, 0x80, 0x78, 0x10, 0xdf, 0xf9,
	0xa8, 0x92, 0x01, 0xec, 0xd0, 0x6e, 0xda, 0x96, 0x5a, 0xe4, 0x38, 0x6d, 0x4a, 0xa3, 0x8b, 0x62,
	0xb6, 0x8b, 0xcf, 0xc7, 0x46, 0xd8, 0xef, 0xbe, 0xca, 0xeb, 0x4e, 0x16, 0xb2, 0xb4, 0xd8, 0x9b,
	0x56, 0xc8, 0xf2, 0xf5, 0xb9, 0x68, 0xb4, 0xaa, 0x9f, 0x9a, 0xae, 0xba, 0xa2, 0xe3, 0xbe, 0xfc,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x28, 0x30, 0x9c, 0x31, 0x70, 0x01, 0x00, 0x00,
}
